### PR TITLE
Update src/gallery.html

### PR DESCRIPTION
**Pull request by MsWebGirl**
Create a gallery page #199 #Hacktoberfest
bootstrap gallery for site. Just insert images.

### CODE REVIEW

**Comment by ashikmeerankutty** [comment]
@MsWebGirl Can you please publish a screenshot here.

**Comment by abhijithvijayan** [comment]
@MsWebGirl Please do close the PR as submit it to the ```release``` branch

**Comment by MsWebGirl** [comment]
Will do

**Comment by abhijithvijayan** [comment]
@MsWebGirl No worries I merged the ```release``` branch with ```master``` and then your PR.
Thanks for the commit.

**Comment by MsWebGirl** [comment]
Thank you!

**Pull request merged**
